### PR TITLE
Add keywords and reserved words

### PR DESCRIPTION
**Pull request by amendlik**
Keywords added:
lyricsto
addlyrics

Reserved words added:
stanza
midiInstrument
title
composer
piece
tagline
arranger
subtitle
subsubtitle
opus
instrument
poet
meter
copyright

### CODE REVIEW

**Comment by yrammos** [comment]
Thanks for your work, @amendlik. I totally understand your reasons for requesting these changes but cannot approve them because your proposed keywords are not considered "reserved keywords", strictly speaking, by the LilyPond lexer. Maintaining a RegEx-based parser is cumbersome as it is, and I have chosen to be very rigorous and consistent, and not succumb to the temptation of ad hoc patches.

**Comment by amendlik** [comment]
@yrammos I appreciate your position on that. Is there perhaps a subset of my changes that you would be able to accept? I would think `addlyrics` and `lyricsto`, at least, would meet your criteria.

Is there a document or source file I could look at to see a canonical list of reserved keywords?

**Comment by yrammos** [comment]
@amendlik, you are right, `addlyrics` and `lyricsto` are in a different 
class, but I fail to see what the problem is. Would you send me a few 
examples? Please allow me some time to work on the issue, if one does 
exist, as it's a busy time.

**Comment by yrammos** [comment]
@amendlik, as for a list of keywords, you need to use the Scheme function `ly:lexer-keywords` to produce it. See http://lilypond.org/doc/v2.19/Documentation/internals/scheme-functions and https://github.com/nsceaux/lyqi/blob/master/make-words.ly.

**Pull request closed without merging**
